<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>
<?php
/**
 * Blog tag claud sidebar template
 *
 * @var $block \Magefan\Blog\Block\Sidebar\TagClaud
 */
?>
<?php $tags = $block->getTags(); ?>

<?php if (count($tags)) { ?>
<div class="block-tagclaud mb-10">
    <div class="title text-xl md:text-2xl font-semibold border-b py-2">
        <?= $escaper->escapeHtml(__('Tags')) ?>
    </div>

    <div class="tagclaud-hld card flex flex-wrap gap-2 shadow-none px-0">
    <?php foreach ($tags as $tag) { ?>
        <?php $title = $tag->getTitle() ?>
        <span class="inline-block border border-gray-300 rounded text-sm text-gray-500 hover:text-white hover:bg-primary px-3 py-1 transition duration-150 ease-out hover:ease-in <?= $escaper->escapeHtml($block->getTagClass($tag)) ?>">
            <a href="<?= $escaper->escapeUrl($tag->getTagUrl()) ?>" title="<?= $escaper->escapeHtml($title) ?>">
                <?= $escaper->escapeHtml($title) ?>
            </a>
        </span>
    <?php } ?>
    </div>
</div>
<?php } ?>
