<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\StoreConfig;
use Magento\Checkout\Block\Cart\Sidebar as SidebarCart;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Theme\ViewModel\SvgIcons;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
$hyvaicons = $viewModels->require(SvgIcons::class);


/** @var StoreConfig $storeConfig */
$storeConfig = $viewModels->require(StoreConfig::class);
$showMiniCart = $storeConfig->getStoreConfig(SidebarCart::XML_PATH_CHECKOUT_SIDEBAR_DISPLAY);

?>
<script>
    function initHeader () {
        return {
            searchOpen: false,
            cart: {},
            isCartOpen: false,
            getData(data) {
                if (data.cart) { this.cart = data.cart }
            },
            isCartEmpty() {
                return !this.cart.summary_count
            },
            toggleCart(event) {
                if (event.detail && event.detail.isOpen !== undefined) {
                    this.isCartOpen = event.detail.isOpen
                    if (!this.isCartOpen && this.$refs && this.$refs.cartButton) {
                        this.$refs.cartButton.focus()
                    }
                } else {
                    <?php
                    /*
                     * The toggle-cart event was previously dispatched without parameter to open the drawer (not toggle).
                     * Keeping this in here for backwards compatibility.
                     */
                    ?>
                    this.isCartOpen = true
                }
            }
        }
    }
    function initCompareHeader() {
        return {
            compareProducts: null,
            itemCount: 0,
            receiveCompareData(data) {
                if (data['compare-products']) {
                    this.compareProducts = data['compare-products'];
                    this.itemCount = this.compareProducts.count;
                }
            }
        }
    }
</script>
<div id="header"
     class="relative z-30 w-full py-5 max-sm:py-2.5"
     x-data="initHeader()"
     @private-content-loaded.window="getData(event.detail.data)"
>
    <div class="block-container flex flex-wrap justify-between max-sm:items-center">

        <div class="flex item-center logo">
            <!--Logo-->
            <?= $block->getChildHtml('logo'); ?>
        </div>

        <div class="flex item-center header-search">
            <!--Search and Search Icon-->
            <?php if ($block->getChildBlock('wizzy.search')): ?>
                <?= $block->getChildHtml('wizzy.search'); ?>
            <?php else: ?>
                <?= $block->getChildHtml('header-search'); ?>
            <?php endif; ?>
        </div>

        <div class="flex items-center gap-x-[6px] md:gap-x-[6px] order-3">
            <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header-call-info')->toHtml(); ?>
            
            <div class="compare">
                <!--Compare Icon-->
                <a id="compare-link"
                class="compare-link btn btn-icon"
                href="<?= $escaper->escapeUrl($block->getUrl('catalog/product_compare/index')) ?>"
                title="<?= $escaper->escapeHtmlAttr(__('Compare Products')) ?>"
                x-data="initCompareHeader()"
                @private-content-loaded.window="receiveCompareData($event.detail.data)"
                :aria-label="`
                        <?= $escaper->escapeHtmlAttr(__('Compare Products')) ?>,
                        ${itemCount > 1
                            ? hyva.str('<?= $escaper->escapeJs(__('%1 Items')) ?>', itemCount)
                            : hyva.str('<?= $escaper->escapeJs(__('%1 Item')) ?>', itemCount)
                        }`"
                >
                    <?= $hyvaicons->compareHtml("w-6 h-6", 24, 24, ["aria-hidden" => "true"]) ?>
                    <span
                        x-text="itemCount"
                        class="absolute -top-1.5 -right-1.5 h-4 min-w-4 p-1 rounded-full bg-primary text-white
                            text-[10px] font-medium leading-none text-center uppercase"
                        aria-hidden="true"
                    ></span>
                </a>
            </div>
            <!-- Wishlist Icon -->
            <div class="custom link wishlist btn btn-icon" data-bind="scope: 'wishlist'">
                <a href="<?= $escaper->escapeUrl($block->getUrl('wishlist')) ?>"
                    title="<?= $escaper->escapeHtmlAttr(__('Wishlist')) ?>"
                    class="wishlist-custom circle-icon-link">
                    <?= $hyvaicons->heartHtml('w-6 h-6', 24, 24, ["aria-hidden" => "true"]); ?>
                    <span class="text sr-only label"><?= $escaper->escapeHtml(__('My Wish List')) ?></span>
                </a>
            </div>

            <!-- Additional Header Elements -->
            <?= $block->getChildHtml('additional') ?>
            <div class="minicart">
                <!--Cart Icon-->
                <?php if ($showMiniCart): ?>
                    <button
                <?php else: ?>
                    <a
                <?php endif ?>
                    id="menu-cart-icon"
                    class="btn btn-icon"
                    x-ref="cartButton"
                    :aria-disabled="isCartEmpty()"
                    :aria-label="`
                        <?= $escaper->escapeHtmlAttr($showMiniCart ? __('Toggle minicart') : __('View cart')) ?>,
                        ${isCartEmpty()
                            ? '<?= $escaper->escapeHtmlAttr(__('Cart is empty')) ?>'
                            : cart.summary_count > 1
                                ? hyva.str('<?= $escaper->escapeHtmlAttr(__('%1 items')) ?>', cart.summary_count)
                                : hyva.str('<?= $escaper->escapeHtmlAttr(__('%1 item')) ?>', cart.summary_count)
                        }`"
                    <?php if ($showMiniCart): ?>
                        @click.prevent.stop="() => {
                            $dispatch('toggle-cart', { isOpen: true })
                        }"
                        @toggle-cart.window="toggleCart($event)"
                        :aria-expanded="isCartOpen"
                        aria-haspopup="dialog"
                    <?php else: ?>
                        href="<?= $escaper->escapeUrl($block->getUrl('checkout/cart/index')) ?>"
                        title="<?= $escaper->escapeHtmlAttr(__('View cart')) ?>"
                    <?php endif ?>
                >
                    <?= $hyvaicons->minicartHtml("h-6 w-6", 24, 24, ["aria-hidden" => "true"]) ?>
                    <span
                        x-text="cart.summary_count"
                        x-show="!isCartEmpty()"
                        x-cloak
                        class="absolute -top-1.5 -right-1.5 h-5 px-2 py-1 rounded-full bg-primary text-white
                            text-xs font-semibold leading-none text-center uppercase tabular-nums"
                        aria-hidden="true"
                    ></span>
                <?php if ($showMiniCart): ?>
                    </button>
                <?php else: ?>
                    </a>
                <?php endif ?>
            </div>
            <div class="csutomer">
                <!--Customer Icon & Dropdown-->
                <?= $block->getChildHtml('customer') ?>
            </div>
        </div>
    </div>

    <!--Cart Drawer-->
    <?= $block->getChildHtml('cart-drawer'); ?>

    <!--Authentication Pop-Up-->
    <?= $block->getChildHtml('authentication-popup'); ?>
</div>
<div class="top-menu">
    <!--Main Navigation-->
    <?= $block->getChildHtml('topmenu') ?>
</div>

