<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>
<?php
/**
 * Blog post list item template
 *
 * @var $block \Magefan\Blog\Block\Post\PostList\Item
 */
?>
<?php
$_post = $block->getPost();
$_postUrl = $escaper->escapeUrl($_post->getPostUrl());
$_postName = $escaper->escapeHtml($_post->getTitle());
?>
<li class="post-holder post-holder-<?= (int)$_post->getId() ?> card rounded-lg border border-gray-300 shadow-none mb-4">
    <div class="post-image">
        <?php $featuredImage = $_post->getFeaturedListImage() ?: $_post->getFeaturedImage(); ?>
            <?php if ($featuredImage) { ?>
                <?php
                $featuredImgAlt = $_post->getData('featured_list_img_alt') ?: $_post->getData('featured_img_alt');
                if (!$featuredImgAlt) {
                    $featuredImgAlt = $_postName;
                }
                ?>
                <div class="post-ftimg-hld">
                    <a href="<?= /*@noEscape*/ $_postUrl ?>"
                    title="<?= /*@noEscape*/ $_postName ?>">
                        <img src="<?= $escaper->escapeUrl($featuredImage) ?>" class="max-h-400 w-full object-cover"
                            alt="<?= $escaper->escapeHtml($featuredImgAlt) ?>" />
                    </a>
                </div>
        <?php } ?>
    </div>
    <div class="post-header mt-3">
        <?= /*@noEscape*/ $block->getInfoHtml() ?>
    </div>
    <div class="post-content">
        <div class="post-title-holder flex items-center justify-between flex-wrap">
                <h2 class="post-title m-0 py-2.5">
                    <a class="post-item-link"
                    href="<?= /*@noEscape*/ $_postUrl ?>">
                        <?= /*@noEscape*/ $_postName ?>
                    </a>
                </h2>

            <?php if ($block->displayAddThisToolbox()) : ?>
                <div class="addthis_toolbox addthis_default_style"
                    addthis:url="<?= /*@noEscape*/ $_postUrl ?>"
                    addthis:title="<?= /*@noEscape*/ $_postName ?>"
                    <?php if ($firstImage = $_post->getFirstImage()) { ?>
                        addthis:media="<?= $escaper->escapeHtml($firstImage) ?>"
                    <?php } ?>>
                    <a class="addthis_button_facebook"></a>
                    <a class="addthis_button_twitter"></a>
                    <a class="addthis_button_email"></a>
                    <a class="addthis_button_compact"></a>
                </div>
            <?php endif; ?>
        </div>
        <div class="post-description clearfix">
            <div class="post-text-hld clearfix">
                <?= /*@noEscape*/ $block->getShorContent() ?>
            </div>
            <a class="post-read-more bg-primary text-white rounded-md font-semibold px-3 py-2 mt-3 float-right"
               href="<?= /*@noEscape*/ $_postUrl ?>"
               title="<?= /*@noEscape*/ $_postName ?>">
                <?= $escaper->escapeHtml(__('Read more &#187;')) ?>
            </a>
        </div>
    </div>
</li>