<?php

/**
 * @var \Magento\Checkout\Block\Onepage\Success $block
 * @var \Magento\Sales\Model\Order $order
 */
$order = $this->getOrder();
?>
<script src="https://apis.google.com/js/platform.js?onload=renderOptIn" async defer></script>
<script>
    window.renderOptIn = function() {
        window.gapi.load('surveyoptin', function() {
            window.gapi.surveyoptin.render({
                // REQUIRED FIELDS
                "merchant_id": 120768863,
                "order_id": "<?= $block->getOrderId() ?>",
                "email": "<?= $order->getCustomerEmail() ?>",
                "delivery_country": "<?= $order->getShippingAddress()->getCountryId() ?>",
                "estimated_delivery_date": "<?= date('Y-m-d', strtotime('+2 days')) ?>"
            });
        });
    }
</script>
<script src="https://apis.google.com/js/platform.js?onload=renderBadge" async defer></script>

<script>
    window.renderBadge = function() {
        var ratingBadgeContainer = document.createElement("div");
        document.body.appendChild(ratingBadgeContainer);
        window.gapi.load('ratingbadge', function() {
            window.gapi.ratingbadge.render(ratingBadgeContainer, {
                "merchant_id": 120768863
            });
        });
    }
</script>