<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\StoreConfig;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

$storeConfig = $viewModels->require(StoreConfig::class);
$maxItemsToDisplay = $storeConfig->getStoreConfig('checkout/sidebar/max_items_display_count');

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>
<script>
    function initCartDrawer() {
        return {
            open: false,
            isLoading: false,
            cart: {},
            maxItemsToDisplay: <?= (int) $maxItemsToDisplay ?>,
            itemsCount: 0,
            getData(data) {
                if (data.cart) {
                    this.cart = data.cart;
                    this.itemsCount = data.cart.items && data.cart.items.length || 0;
                    this.setCartItems();
                }
                this.isLoading = false;
            },
            cartItems: [],
            getItemCountTitle() {
                return hyva.strf('<?= $escaper->escapeJs(__('%0 of %1 products in cart displayed')) ?>', this.maxItemsToDisplay, this.itemsCount)
            },
            setCartItems() {
                this.cartItems = this.cart.items && this.cart.items.sort((a, b) => b.item_id - a.item_id) || [];

                if (this.maxItemsToDisplay > 0) {
                    this.cartItems = this.cartItems.slice(0, parseInt(this.maxItemsToDisplay, 10));
                }
            },
            deleteItemFromCart(itemId) {
                this.isLoading = true;

                const formKey = hyva.getFormKey();
                const postUrl = BASE_URL + 'checkout/sidebar/removeItem/';

                fetch(postUrl, {
                    "headers": {
                        "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    },
                    "body": "form_key=" + formKey + "&item_id=" + itemId,
                    "method": "POST",
                    "mode": "cors",
                    "credentials": "include"
                }).then(response => {
                    if (response.redirected) {
                        window.location.href = response.url;
                    } else if (response.ok) {
                        return response.json();
                    } else {
                        window.dispatchMessages && window.dispatchMessages([{
                            type: 'warning',
                            text: '<?= $escaper->escapeJs(__('Could not remove item from quote.')) ?>'
                        }]);
                        this.isLoading = false;
                    }
                }).then(result => {
                    window.dispatchMessages && window.dispatchMessages([{
                        type: result.success ? 'success' : 'error',
                        text: result.success
                            ? '<?= $escaper->escapeJs(__('You removed the item.')) ?>'
                            : result.error_message
                    }], result.success ? 5000 : 0)
                    window.dispatchEvent(new CustomEvent('reload-customer-section-data'));
                });
            },
            scrollLock(use = true) {
                document.body.style.overflow = use ? "hidden" : "";
            },
            toggleCartDrawer(event) {
                if (event.detail && event.detail.isOpen !== undefined) {
                    if (event.detail.isOpen) {
                        this.openCartDrawer();
                    } else {
                        this.open = false;
                        this.scrollLock(false);
                        this.$refs && this.$refs.cartDialogContent && hyva.releaseFocus(this.$refs.cartDialogContent);
                    }
                } else {
                    <?php
                    /*
                     * The toggle-cart event was previously dispatched without parameter to open the drawer (not toggle).
                     * Keeping this in here for backwards compatibility.
                     */
                    ?>
                    this.openCartDrawer()
                }
            },
            openCartDrawer() {
                this.open = true;
                this.scrollLock(true);
                this.$nextTick(() => {
                    this.$refs && this.$refs.cartDialogContent && hyva.trapFocus(this.$refs.cartDialogContent)
                })
            },
            closeCartDrawer() {
                this.$dispatch('toggle-cart', { isOpen: false })
            },
            getSectionDataExtraActions() {
                if (!this.cart.extra_actions) {
                    return '';
                }

                const contentNode = document.createElement('div');
                contentNode.innerHTML = this.cart.extra_actions;

                hyva.activateScripts(contentNode);

                return contentNode.innerHTML;
            }
        }
    }
</script>
<section x-cloak
         x-show="cart"
         id="cart-drawer"
         x-data="initCartDrawer()"
         @private-content-loaded.window="getData($event.detail.data)"
         @toggle-cart.window="toggleCartDrawer($event)"
         @keydown.escape="closeCartDrawer"
>
    <div role="dialog"
         aria-labelledby="cart-drawer-title"
         aria-modal="true"
         :aria-hidden="!open"
         class="fixed inset-y-0 right-0 z-30 flex max-w-full">
        <div class="backdrop"
             x-show="open"
             x-transition:enter="ease-in-out duration-500"
             x-transition:enter-start="opacity-0"
             x-transition:enter-end="opacity-100"
             x-transition:leave="ease-in-out duration-500"
             x-transition:leave-start="opacity-100"
             x-transition:leave-end="opacity-0"
             role="button"
             @click="closeCartDrawer"
             aria-label="<?= $escaper->escapeHtmlAttr(__('Close minicart')) ?>"></div>
        <div class="relative w-screen max-w-md shadow-2xl"
             x-show="open"
             x-transition:enter="transform transition ease-in-out duration-500 sm:duration-700"
             x-transition:enter-start="translate-x-full"
             x-transition:enter-end="translate-x-0"
             x-transition:leave="transform transition ease-in-out duration-500 sm:duration-700"
             x-transition:leave-start="translate-x-0"
             x-transition:leave-end="translate-x-full"
             x-ref="cartDialogContent"
             role="region"
             :tabindex="open ? 0 : -1"
             aria-label="<?= $escaper->escapeHtmlAttr(__('My Cart')) ?>"

        >
            <div class="relative flex flex-col h-full max-h-screen bg-white shadow-xl">
                <?= $block->getChildHtml('cart-drawer.top'); ?>

                <header class="relative border-b px-4 py-4 sm:px-6">
                    <p id="cart-drawer-title" class="text-lg font-medium leading-7 text-gray-900 mb-0">
                        <strong><?= $escaper->escapeHtml(__('My Cart')) ?></strong>
                        <span class="items-total text-xs"
                              x-show="maxItemsToDisplay && maxItemsToDisplay < itemsCount"
                              x-text="getItemCountTitle()">
                        </span>
                    </p>
                </header>

                <?= $block->getChildHtml('cart-drawer.items.before'); ?>

                <template x-if="!itemsCount">
                    <div class="relative px-4 py-6 bg-white border-bs sm:px-6 border-container">
                        <?= $escaper->escapeHtml(__('Cart is empty')) ?>
                    </div>
                </template>

                <template x-if="itemsCount">
                    <div class="relative grid gap-4 px-1 py-3 sm:px-3 bg-white border-container overflow-y-auto overscroll-y-contain mb-36">
                        <template x-for="item in cartItems">
                            <div class="flex items-start bg-gray-100 hover:bg-gray-100 rounded-lg p-3 space-x-4 transition duration-150 ease-in-out">
                                <a :href="item.product_url"
                                   class="w-1/4"
                                   :aria-label="hyva.strf('<?= $escaper->escapeJs(__('Product "%0"')) ?>', item.product_name)"
                                >
                                    <img
                                        :src="item.product_image.src"
                                        :width="item.product_image.width"
                                        :height="item.product_image.height"
                                        loading="lazy"
                                        alt=""
                                    />
                                </a>
                                <div class="w-3/4">
                                    <p class="text-base font-semibold mb-0">
                                        <span x-html="item.qty"></span> x <span x-html="item.product_name"></span>
                                    </p>
                                    <div class="flex flex-wrap justify-between">
                                        <p class="text-lg text-primary font-semibold mb-0"><span x-html="item.product_price"></span></p>
                                        <p class="hidden text-sm"><span x-html="item.product_sku"></span></p>
                                        <div x-show="item.mp_brand" class="mp-brand-item">
                                            <template x-if="item.brand_logo">
                                                <div class="product-brand-logo">
                                                    <a :href="item.brand_url">
                                                        <template x-if="item.swatch_type == 1">
                                                            <img :style="{ width: item.brand_width + 'px', height: item.brand_height + 'px', 'background-color': item.swatch_value }">
                                                        </template>
                                                        <template x-if="item.swatch_type != 1">
                                                            <img :src="item.image_url" :title="item.brand_value" :alt="item.brand_value" :style="{ width: 'auto', height: '24px' }">
                                                        </template>
                                                    </a>
                                                </div>
                                            </template>
                                            <template x-if="item.brand_name">
                                                <div class="product-brand-name">
                                                    <a :href="item.brand_url">
                                                        <span :title="item.brand_value" class="font-semibold hover:underline" x-text="item.brand_value"></span>
                                                    </a>
                                                </div>
                                            </template>
    
                                            <template x-if="item.show_desc">
                                                <div class="product-brand-desc text-sm">
                                                    <p x-html="item.short_desc"></p>
                                                    <template x-if="item.desc_is_shorten">
                                                        <p>
                                                            <a :href="item.product_url">
                                                                <i x-text="'Read more'"></i>
                                                            </a>
                                                        </p>
                                                    </template>
                                                </div>
                                            </template>
                                        </div>
                                    </div>
                                    <template x-for="option in item.options">
                                        <div class="pt-2">
                                            <p class="font-semibold" x-text="option.label + ':'"></p>
                                            <p class="text-secondary" x-html="option.value"></p>
                                        </div>
                                    </template>                                    
                                    <div class="flex">
                                        <a :href="item.configure_url"
                                           x-show="item.product_type !== 'grouped' && item.is_visible_in_site_visibility"
                                           class="inline-flex p-1 mr-2 btn btn-primary"
                                           :aria-label="hyva.strf('<?= $escaper->escapeJs(__('Edit product "%0"')) ?>', item.product_name)"
                                        >
                                            <?= $heroicons->pencilHtml('', 16, 16, ['aria-hidden' => 'true']); ?>
                                        </a>
                                        <button type="button"
                                                class="inline-flex p-1 btn btn-primary"
                                                @click="deleteItemFromCart(item.item_id)"
                                                :aria-label="hyva.strf('<?= $escaper->escapeJs(__('Remove product "%0" from cart')) ?>', item.product_name)"
                                        >
                                            <?= $heroicons->trashHtml('', 16, 16, ['aria-hidden' => 'true']); ?>
                                        </button>
                                    </div>

                                </div>
                            </div>
                        </template>
                    </div>
                </template>

                <template x-if="itemsCount">
                    <div class="absolute bottom-0 right-0 left-0">
                        <?= $block->getChildHtml('cart-drawer.totals.before'); ?>

                        <div class="relative bg-white border-t grid py-0">
                            <div class="w-full flex justify-between px-3 py-5 pr-6 space-x-4 transition duration-150 ease-in-out rounded-lg border-b">
                                <p class="flex justify-between mb-0 w-full items-center"><?= $escaper->escapeHtml(__('Cart Subtotal')) ?> : <span x-html="cart.subtotal" class="text-base font-semibold text-primary"></span></p>
                            </div>
                            <div class="w-full px-3 py-5 space-x-4 transition duration-150 ease-in-out rounded-lg text-center">
                                <a @click.prevent.stop="closeCartDrawer; $dispatch('toggle-authentication',
                                    {url: '<?= $escaper->escapeUrl($block->getUrl('checkout')) ?>'});"
                                   href="<?= $escaper->escapeUrl($block->getUrl('checkout')) ?>"
                                   class="inline-flex btn btn-primary"
                                >
                                    <?= $escaper->escapeHtml(__('Checkout')) ?>
                                </a>
                                <span><?= $escaper->escapeHtml(__('or')) ?></span>
                                <a href="<?= $escaper->escapeUrl($block->getUrl('checkout/cart')) ?>"
                                   class="underline"
                                >
                                    <?= $escaper->escapeHtml(__('View and Edit Cart')) ?>
                                </a>
                            </div>
                            <div x-html="getSectionDataExtraActions()"></div>
                            <?= $block->getChildHtml('extra_actions'); ?>
                        </div>
                    </div>
                </template>

                <?= $block->getChildHtml('cart-drawer.bottom'); ?>
            </div>

            <button
                type="button"
                @click="closeCartDrawer"
                aria-label="<?= $escaper->escapeHtmlAttr(__('Close minicart')) ?>"
                class="absolute top-0 right-2 p-4 mt-0.5 text-gray-300 transition-colors hover:text-black"
            >
                <?= $heroicons->xHtml('', 24, 24, ['aria-hidden' => 'true']); ?>
            </button>
        </div>
        <?= $block->getChildHtml('loading') ?>
    </div>

</section>
