<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Shop By Hyva Compatibility
 */

declare(strict_types=1);

use Amasty\Shopby\Block\Navigation\FilterRenderer\Category;
use Amasty\Shopby\Model\Layer\Filter\CategoryItems;
use Amasty\Shopby\Model\Layer\Filter\Item;
use Amasty\Shopby\Model\Source\SubcategoriesExpand;
use Amasty\ShopbyBase\Model\FilterSetting;
use Amasty\ShopbyHyvaCompatibility\ViewModel\ProductListAjax;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var FilterSetting $filterSetting */
/** @var Item $filterItem */
/** @var Category $block */
/** @var CategoryItems $filterItems */
/** @var ViewModelRegistry $viewModels */

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var ProductListAjax $productListAjax */
$productListAjax = $viewModels->require(ProductListAjax::class);

$filterItems = $block->getFilter()->getItems();
$categoryHelper = $block->getCategoryHelper();
$filterSetting = $block->getFilterSetting();
$filterSubcategoriesView = $block->isFolding();
$isFlyOut = !$filterSubcategoriesView;
$filterSubcategoriesType = $filterSubcategoriesView
    ? 'labelsFolding'
    : 'flyOut';
$filterFoldingClass = $filterSubcategoriesView ? '-folding' : '';
$isParent = $block->isParent($filterItems, $block->getPath());
$showProductQuantities = $filterSetting->getShowProductQuantities();
$filterPathItems = $filterItems->getItems($block->getPath());
$isByClickSetting = $filterSubcategoriesView && $filterSetting->getSubcategoriesExpand() == SubcategoriesExpand::BY_CLICK;

$firstLevelHaveCollapsible = false;
foreach ($filterPathItems as $filterItem) {
    $currentPath = ($block->getPath() ?: $filterItems->getStartPath()) . '/' . $filterItem->getValueString();
    if ($filterItems->getItemsCount($currentPath)) {
        $firstLevelHaveCollapsible = true;
        break;
    }
}
?>
<?php if (count($filterPathItems)): ?>
    <?php foreach ($filterPathItems as $filterItem): ?>
        <?php
        $currentPath = ($block->getPath() ?: $filterItems->getStartPath()) . '/' . $filterItem->getValueString();
        $filterItemId = uniqid();
        $filterItemUrl = $filterItem->getUrl();
        $classes = '';
        if (!$filterItem->getCount()) {
            $classes .= ' -empty-value ';
        }
        if ($filterItems->getItemsCount($currentPath)) {
            $classes .= ' -is-collapsible ';
        }
        $classes .= $block->isExpandByClick($currentPath) || $firstLevelHaveCollapsible ? ' relative ' : ' is-expanded ';
        if ($block->getFilter()->getItemsCount()) {
            $classes .= ' -filter-parent ';
        }
        if ($isFlyOut) {
            $classes .= ' flyout-element ';
        }
        ?>
        <script>
          function initInput_<?= $escaper->escapeHtml($filterItemId); ?>() {
            return deepMerge({}, initInput(), {
              isSelected: Boolean(<?= /** @noEscape */ $block->checkedFilter($filterItem)?>),
              value: '<?= $escaper->escapeHtmlAttr($filterItem->getValueString()); ?>',
              name: '<?= /* @noEscape */ $block->getFilter()->getRequestVar(); ?>',
              type: '<?= /* @noEscape */ $block->getInputType() ?>'
            })
          }
        </script>
        <li x-data="initInput_<?= $escaper->escapeHtml($filterItemId); ?>()" x-init="openParentFilter($el)"
            x-bind="eventListeners"
            x-spread="eventListeners"
            class="item item-category flex flex-wrap items-center py-1 px-2 hover:text-black <?= $escaper->escapeHtmlAttr($classes); ?>"
            data-label="<?= /* @noEscape */ $block->stripTags($filterItem->getOptionLabel()) ?>"
            <?php if ($isFlyOut): ?>
            @mouseenter="positioned = true"
            @mouseleave="positioned = false"
            :class="{ 'relative': positioned }"
            <?php endif; ?>>
            <?php if ($block->isExpandByClick($currentPath)): ?>
                <button type="button"
                        class="filter-options-title absolute top-[5px] left-0 flex justify-between items-center cursor-pointer hover:text-secondary-darker border-container"
                        @click="open = !open" :class="{'collapsed' : !open, 'opened' : open}"
                        :aria-expanded="open ? 'true' : 'false' ">
                    <span class="py-1 px-1 rounded border border-container">
                        <?= $heroicons->chevronDownHtml(
                            'transition-transform transform duration-300 ease-in-out',
                            12,
                            12,
                            [":class" => "{ 'rotate-180': open }"]
                        ); ?>
                    </span>
                </button>
            <?php endif; ?>

            <?php if ($filterItem->getCount() > 0): ?>
                <?php $inputId = 'amshopby-' . $block->getFilter()->getRequestVar() . '-' . $filterItem->getValueString() . ' - ' . uniqid() ?>
                <div class="filter-row category-filter-row flex items-center max-w-full w-full" role="radiogroup"
     aria-label="<?= $escaper->escapeHtmlAttr($filterItem->getOptionLabel()) ?>">
    <?php $filterUniqId = uniqid(); ?>
    <label for="amfilter-id-<?= $escaper->escapeHtmlAttr($inputId) ?>" class="flex items-center cursor-pointer mb-0">
        <input 
            class="hidden peer" 
            id="amfilter-id-<?= $escaper->escapeHtmlAttr($inputId) ?>" 
            name="amshopby[<?= $escaper->escapeHtmlAttr($block->getFilter()->getRequestVar()); ?>][]"
            value="<?= $escaper->escapeHtmlAttr($filterItem->getValueString()); ?>" 
            type="<?= /* @noEscape */ $block->getInputType() ?>" 
            @change="$dispatch('amApplyInputChanged', {
                value: '<?= $escaper->escapeHtmlAttr($filterItem->getValueString()); ?>',
                element: $el,
                name: '<?= /* @noEscape */ $block->getFilter()->getRequestVar(); ?>'
            })"
            :checked="isSelected"
        />
        <span class="w-5 h-5 flex items-center justify-center border border-gray-300 peer-checked:border-none peer-checked:bg-red-500 peer-checked:text-white rounded-sm">
    <svg 
        xmlns="http://www.w3.org/2000/svg" 
        class="w-4 h-4 text-white peer-checked:block" 
        fill="none" 
        viewBox="0 0 24 24" 
        stroke="currentColor" 
        stroke-width="2">
        <path stroke-linecap="round" stroke-linejoin="round" d="M5 13l4 4L19 7" />
    </svg>
</span>

        <span class="ml-2 hidden">
            <?= $escaper->escapeHtml($filterItem->getOptionLabel()) ?>
        </span>
    </label>
    <a class="flex align-middle max-w-full hover:text-gray-dark w-full justify-start items-start ml-2 leading-tight <?= $isParent ? 'amshopby-filter-parent' : '' ?>"
       data-am-js="filter-item-default"
       href="<?= $escaper->escapeUrl($filterItem->getUrl()) ?>"
       title="<?= $escaper->escapeHtmlAttr($filterItem->getOptionLabel()); ?>"
       :class="{ 'amshopby-link-selected text-gray-dark': isSelected }"
       @click.prevent.stop="$dispatch('amApplyInputChanged', {
           value: '<?= $escaper->escapeHtmlAttr($filterItem->getValueString()); ?>',
           element: $event.currentTarget,
           name: '<?= /* @noEscape */ $block->getFilter()->getRequestVar(); ?>'
       })"
       <?= $filterItem->isAddNofollow() ? ' rel="nofollow"' : '' ?>>
        <?php if ($block->getFilter()->useLabelsOnly()): ?>
            <span class="label max-w-[90%] text-gray-500 break-words leading-tight <?= /**@noEscape */ $block->getLevel() == 1 ? 'font-normal' : ''; ?>">
                <?= /* @noEscape */ $filterItem->getOptionLabel() ?></span>
        <?php else: ?>
            <?php if ($block->isShowThumbnail($filterItem->getValue())): ?>
                <img src="<?= /* @noEscape */ $categoryHelper->getCategoryImageUrl($filterItem->getValue()) ?>"
                     class="am-category-image mr-1 inline-block mt-[2px]"
                     title="<?= $escaper->escapeHtmlAttr($filterItem->getOptionLabel()); ?>"
                     alt="<?= $escaper->escapeHtmlAttr($filterItem->getOptionLabel()); ?>"
                     height="<?= /* @noEscape */ $categoryHelper->getCategoryFilterImageSize(); ?>"
                     width="<?= /* @noEscape */ $categoryHelper->getCategoryFilterImageSize(); ?>"/>
            <?php endif; ?>
            <?php if ($block->getFilter()->useLabelsAndImages()): ?>
                <span class="label <?= /**@noEscape */ $block->getLevel() == 1 ? 'font-semibold' : ''; ?>">
                    <?= /* @noEscape */ $filterItem->getOptionLabel() ?></span>
            <?php endif; ?>
        <?php endif; ?>
        <?php if ($block->isShowProductQuantities($showProductQuantities)): ?>
            <span class="count ml-auto text-gray-500 <?= /* @noEscape */ $isFlyOut ? 'fly-out-count' : '' ?>">
                <?= /* @noEscape */ "(" . $filterItem->getCount() . ")"; ?>
                <span class="filter-count-label sr-only">
                    <?php $title = ($filterItem->getCount() == 1) ? __('item') : __('items');?>
                    <?= /* @noEscape */ $escaper->escapeHtml($title) ?>
                </span>
            </span>
        <?php endif; ?>
    </a>
</div>

            <?php endif; ?>


            <?php if ($filterItems->getItemsCount($currentPath)): ?>
                <?php
                $level = $block->getLevel();
                $itemsClass = " items items-children relative w-full mt-2 ml-0 level-{$level} {$filterFoldingClass} ";

                if ($isFlyOut) {
                    $itemsClass .= ' absolute z-30 px-6 py-4 md:m-0 shadow-lg bg-container-lighter md:left-full left-0 md:-top-2 top-6 w-full ';
                }
                ?>
                <ul class="<?= /* @noEscape */ $itemsClass ?>"
                    <?php if ($isFlyOut): ?>
                        :class="{ 'hidden': !positioned, 'block': positioned }"
                    <?php endif; ?>
                    <?php if ($isByClickSetting): ?>
                        x-show="open" x-cloak
                    <?php endif; ?>>
                    <?= /* @noEscape */ $block->renderChildrenItems($currentPath); ?>
                </ul>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
<?php endif; ?>
