<?php if ($block->getHelper()->isEnabledExtension()): ?>
    <div class="order-information flex gap-3">
        <form name="order_tracking" id="order_tracking" class="flex-grow" 
              x-data="orderTrackingForm" 
              x-on:submit.prevent="sendRequest('<?= $block->getUrl('ordertracking/ordertracking/track') ?>')">
            <?= $block->getBlockHtml('formkey') ?>
            <fieldset class="border p-4 rounded-md">
                <h3 class="font-bold text-primary mb-4"><?= $escaper->escapeHtml(__('Order Information')) ?></h3>
    
                <div class="mb-4">
                    <label for="order_id" class="block text-sm font-medium mb-1">
                        <?= $escaper->escapeHtml(__('Order Id')) ?>
                    </label>
                    <input type="text" name="order_id" id="order_id" x-model="orderId" required
                           class="w-full border rounded-md p-2 border-gray-300"/>
                </div>
    
                <div class="mb-4">
                    <label for="email_address" class="block text-sm font-medium mb-1">
                        <?= $escaper->escapeHtml(__('Email Address')) ?>
                    </label>
                    <input type="email" name="email" id="email" x-model="email" required
                           class="w-full border rounded-md p-2 border-gray-300"/>
                </div>
    
                <div class="text-right">
                    <button type="submit" class="btn btn-primary hover:btn-primary-lighter">
                        <?= $escaper->escapeHtml(__('Track Order')) ?>
                    </button>
                </div>
            </fieldset>
        </form>
    
        <div id="orderinfo" class="w-1/3"></div>
    </div>
<?php endif; ?>

<script>
    document.addEventListener('alpine:init', () => {
        console.log('Alpine initialized');
        Alpine.data('orderTrackingForm', () => ({
            orderId: '',
            email: '',
            orderInfo: '',

            async sendRequest(url) {
                try {
                    const formData = new FormData();
                    formData.append('order_id', this.orderId);
                    formData.append('email', this.email);
                    formData.append('form_key', hyva.getFormKey());

                    const response = await fetch(url, {
                        method: 'POST',
                        body: formData,
                    });

                    if (response.ok) {
                        const responseText = await response.text();
                        document.getElementById('orderinfo').innerHTML = responseText;
                    } else {
                        console.error("Fetch failed:", response.status, response.statusText);
                        document.getElementById('orderinfo').innerHTML = 'An error occurred while tracking your order.';
                    }
                } catch (error) {
                    console.error("Error during fetch:", error);
                    document.getElementById('orderinfo').innerHTML = 'An unexpected error occurred.';
                }
            },
        }));
    });
</script>
