<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;

/** @var ViewModelRegistry $viewModels */
/** @var HyvaElsner\HomeCustomization\Block\Widget\CategoryCollection $block */
/** @var Escaper $escaper */

$label = $block->getData('label');
$label = !empty($label) ? $label : "Label";
$viewAllCategoriesLabel = $block->getData('view_all_categories_label') ?? "";
$viewAllCategoriesLink = $block->getData('view_all_categories_link') ?? "";
$showTitle = !empty($label) || !empty($viewAllCategoriesLabel);
$hideContainerBorder = $block->getData('hide_container_border') ?? false;
$categoryImages = $block->getCategoryImages();
$defaultWidth = $block->getData('image_default_width') ?? false;
$defaultHeight = $block->getData('image_default_height') ?? false;
$uniqId = '_' . uniqid();
$linkTarget = $block->getData('category_link_target') ?? "_self";
$sectionClasses = $escaper->escapeHtmlAttr($block->getData('section_classes'));
$imageBorderWidth = $block->getData('image_border_width') ?? false;
$imageBorderRadius = $block->getData('image_border_radius') ?? false;
?>
<section class="section relative py-5 sm:py-10 <?= $sectionClasses ?>">
    <?php if ($showTitle) { ?>
        <div class="flex-wrap flex justify-center sm:justify-between items-baseline mb-2 sm:mb-3">
            <?php if (!empty($label)) { ?>
                <h2 class="text-center sm:text-left mb-0">
                    <?= $escaper->escapeHtml(__($label)) ?>
                </h2>
            <?php } ?>
            <?php if (!empty($viewAllCategoriesLabel)) { ?>
                <a href="<?= $escaper->escapeUrl($viewAllCategoriesLink) ?>" class="text-blue-700 text-lg leading-7 font-semibold">
                    <?= $escaper->escapeHtml(__($viewAllCategoriesLabel)) ?>
                </a>
            <?php } ?>
        </div>
    <?php } ?>
    <div style="place-items: start;" class="place-items-start grid grid-cols-3 gap-3 lg:grid-cols-7 lg:gap-4" style="<?= $hideContainerBorder ? "border:none;" : "" ?>">
        <?php foreach ($categoryImages as $item) { ?>
            <a href="<?= !empty($item->getCategoryUrl()) ? $escaper->escapeUrl($item->getCategoryUrl()) : "#" ?>" class="category-link" target="<?= $escaper->escapeHtmlAttr($linkTarget) ?>">
                <div class="group cursor-pointer relative overflow-hidden isolate flex flex-col items-center justify-center">
                    <div class="inline-flex justify-center items-center col-start-1 row-start-1 border border-[#D4D4D4] rounded-[6px] w-full lg:scale-95 lg:group-hover:scale-100 transition-all duration-300 min-h-[152px]">
                        <img src="<?= !empty($item->getExternalCategoryImage()) ? $escaper->escapeUrl($item->getExternalCategoryImage()) : $escaper->escapeHtmlAttr($item->getCategoryImage()) ?>" alt="Category Images" loading="lazy" class="object-contai w-auto max-w-full max-h-full" style="     image-rendering: -moz-crisp-edges;         /* Firefox */
                                    image-rendering:   -o-crisp-edges;         /* Opera */
                                    image-rendering: -webkit-optimize-contrast;/* Webkit (non-standard naming) */
                                    image-rendering: crisp-edges;
                                    -ms-interpolation-mode: nearest-neighbor;  /* IE (non-standard property) */                                    
                                    <?= $imageBorderRadius ? 'border-radius:' . $imageBorderRadius . ';' : '' ?>
                        "
                        <?php if (!empty($defaultWidth)) { ?>
                            width="<?= $defaultWidth; ?>" 
                        <?php } ?>
                        <?php if (!empty($defaultHeight)) { ?>
                            height="<?= $defaultHeight; ?>"
                        <?php } ?>
                        >
                    </div>

                    <?php if (!empty($item->getCategoryDescription())) { ?>
                        <span class="block w-full xl:text-xl max-xl:text-lg max-sm:text-sm max-sm:mt-[11px] font-medium text-black cursor-pointer text-center">
                            <span class=""><?= $escaper->escapeUrl(__($item->getCategoryDescription())) ?></span>
                        </span>
                    <?php } ?>
                    <?php if (!empty($item->getCategoryName())) { ?>
                        <span class="block w-full xl:text-xl max-xl:text-lg max-sm:text-sm max-sm:mt-[11px] font-medium text-black cursor-pointer text-center">
                            <span class=""><?= $escaper->escapeUrl(__($item->getCategoryName())) ?></span>
                        </span>
                    <?php } ?>
                </div>
            </a>
        <?php }?>
    </div>
</section>