<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\StoreConfig;
use Magento\Framework\Escaper;

/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */

$storeConfig = $viewModels->require(StoreConfig::class);
$heroicons = $viewModels->require(HeroiconsOutline::class);
$storePhoneNumber = $storeConfig->getStoreConfig('general/store_information/phone') ?? '';
$storeEmail = $storeConfig->getStoreConfig('trans_email/ident_general/email') ?? '';

?>
<h2 class="text-primary text-3xl font-bold mb-4">
    <span><?= $escaper->escapeHtml(__('Contact Details')) ?></span>
</h2>
<h3 class="title-font text-lg font-semibold mb-0"><?= $escaper->escapeHtml($storeConfig->getStoreConfig('general/store_information/name') ?? ''); ?></h3>
<address class="mb-4">
    <?= $escaper->escapeHtml($storeConfig->getStoreConfig('general/store_information/street_line1') ?? ''); ?><br/>
    <?= $escaper->escapeHtml($storeConfig->getStoreConfig('general/store_information/city') ?? ''); ?><br/>
    <?= $escaper->escapeHtml($storeConfig->getStoreConfig('general/store_information/postcode') ?? ''); ?><br/>
</address>
<ul>
    <li>
		<?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('contact_store_timing_details')->toHtml();?>
    </li>
    <?php if ($storePhoneNumber): ?>
    <li class="mt-6">
        <div class="mb-3">
            <p class="title-font font-semibold mb-0"><?= __("Gives us Ring:") ?></p>
            <?= $heroicons->phoneHtml("w-5 h-5 inline mr-1 text-primary", 25, 25) ?>
            <a class="inline text-primary font-semibold" href="tel:<?= $escaper->escapeHtmlAttr(preg_replace("/[^0-9+]/", "", $storePhoneNumber)) ?>">
                <?= $escaper->escapeHtml($storePhoneNumber); ?>
            </a>
        </div>
    </li>
    <?php endif; ?>
    <li>
        <div>
            <p class="title-font font-semibold"><?= __("OR Drop Us an Email") ?></p>
            <p class="w-full mx-auto leading-relaxed text-base mb-0"><?= __("you can also reach us on email, please email us:") ?></p>
            <span class="text-primary hover:text-primary-darker">
                <?= $heroicons->mailHtml("w-5 h-5 inline mr-1 font-semibold", 25, 25) ?>
                <a href="mailto:<?= $escaper->escapeHtmlAttr($storeEmail); ?>" class="font-semibold underline">
                    <?= $escaper->escapeHtml($storeEmail); ?>
                </a>
            </span>
        </div>
    </li>
</ul>
