<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Currency;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

/** @var Currency $currencyViewModel */
$currencyViewModel = $viewModels->require(Currency::class);
?>
<?php if ($currencyViewModel->getCurrencyCount() > 1): ?>
    <?php $currencies = $currencyViewModel->getCurrencies(); ?>
    <?php $currentCurrencyCode = $currencyViewModel->getCurrentCurrencyCode(); ?>
    <div x-data="{ open: false }"
         class="currency-header"
    >
        <div class="relative inline-block text-left">
            <div>
                <button @click.prevent="open = !open"
                        @click.outside="open = false"
                        @keydown.window.escape="open=false"
                        type="button"
                        class="flex items-center"
                        aria-haspopup="true"
                        :aria-expanded="open"
                >
                    <?= $escaper->escapeHtml($currentCurrencyCode) ?>
                    <?= $heroiconsSolid->chevronDownHtml("flex self-center h-5 w-5 -mr-1 ml-2", 25, 25) ?>
                </button>
            </div>
            <nav x-cloak=""
                 x-show="open"
                 class=""
                 aria-labelledby="currency-heading"
            >
                <div class="my-1">
                    <?php foreach ($currencies as $code => $name): ?>
                        <?php if ($code != $currentCurrencyCode): ?>
                            <button
                               role="link"
                               class="block px-4 py-2 lg:px-5 lg:py-2 hover:bg-gray-100 w-full"
                               aria-describedby="currency-heading"
                               @click.prevent='hyva.postForm(<?= /* @noEscape */ $currencyViewModel->getSwitchCurrencyPostData($code) ?>)'
                            >
                                <?= $escaper->escapeHtml($code) ?>
                            </button>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </div>
            </nav>
        </div>
    </div>
<?php endif; ?>
